In [4]:
import tensorflow as tf
import numpy as np

### 1. Shape, Rank, Axis

rank: [가 몇 개 인지

shape: (rank 개수만큼의 요소)

axis: 제일 안쪽에 있는게 큰 값

ex) [shape:1, axis = 0
    [shape:2, axis = 1
        [shape:3, axis = 2
            shape:4 [1,2,3,4], axis = 3
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16], 
            [17,18,19,20],
            [21,22,23,24]
        ]
    ]
    ]

In [5]:
t = tf.constant([1,2,3,4])
tf.shape(t).numpy()

array([4])

In [6]:
# 2차원
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).numpy()

array([2, 2])

In [8]:
# 4차원
t = tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16], 
            [17,18,19,20],
            [21,22,23,24]
        ]
    ]
                ])
tf.shape(t).numpy()

array([1, 2, 3, 4])

### 2. Matmul vs multiply

In [13]:
# 2x2와 2x1의 곱의 결과: 2x1
matrix1 = tf.constant([[1.,2.],[3.,4.]])
matrix2 = tf.constant([[1.],[2.]])
print("Metrix 1 shape", matrix1.shape)
print("Metrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).numpy

#(matrix2*matrix2).numpy() # 이렇게하면 안됨

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)
[[1.]
 [4.]]


broadcasting: warning!!!!!

In [20]:
matrix1 = tf.constant([[3.],[3.]])
matrix2 = tf.constant([[2.],[2.]])

(matrix1 + matrix2).numpy()

array([[5.],
       [5.]], dtype=float32)

In [22]:
matrix1 = tf.constant([[1.,2.]])
matrix2 = tf.constant([[3.],[4.]])

(matrix1 + matrix2).numpy()

array([[4., 5.],
       [5., 6.]], dtype=float32)

### 3. Reduce mean/ sum

In [25]:
tf.reduce_mean([1,2], axis=0).numpy()

1

In [26]:
x = [[1.,2.],
     [3.,4.]]
tf.reduce_mean(x).numpy()

2.5

In [27]:
tf.reduce_mean(x, axis=0).numpy() # axis=0: 세로

array([2., 3.], dtype=float32)

In [28]:
tf.reduce_mean(x, axis=1).numpy() # axis=1: 가로

array([1.5, 3.5], dtype=float32)

In [29]:
tf.reduce_mean(x, axis=-1).numpy() # axis=1: 가로

array([1.5, 3.5], dtype=float32)

In [30]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).numpy()

5.0

### 4. Argmax: 가장 큰 값을 가지는 공간의 인덱스 번호 반환

In [31]:
x = [[0,1,2],
     [2,1,0]]
tf.argmax(x, axis=0).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 0], dtype=int64)>>

In [32]:
tf.argmax(x, axis=1).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 0], dtype=int64)>>

In [33]:
tf.argmax(x, axis=-1).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 0], dtype=int64)>>

### 5. Reshape

reshape에서 -1의 의미

x.reshape(-1,1) = x.reshape(12,1)

x.reshape(-1,2) = x.reshape(6,2)

x.reshape(-1,3) = x.reshape(4,3)

In [35]:
t = np.array([[[0,1,2],
               [3,4,5]],
               [[6,7,8],
                [9,10,11]]])
t.shape

(2, 2, 3)

In [36]:
tf.reshape(t, shape=[-1,3]).numpy() 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
tf.reshape(t, shape=[-1,1,3]).numpy()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [42]:
tf.squeeze([[0],[1],[2]]).numpy()

array([0, 1, 2])

In [47]:
tf.expand_dims([0,1,2,3],1).numpy()

array([[0],
       [1],
       [2],
       [3]])

### 6. One hot

In [48]:
tf.one_hot([[0],[1],[2],[0]], depth=3).numpy() # depth: 전체 인덱스 수
# 결과: rank가 늘어남

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [49]:
t = tf.one_hot([[0],[1],[2],[0]], depth=3)
tf.reshape(t, shape=[-1,3]).numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

### 7. Casting

In [50]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy()

array([1, 2, 3, 4])

In [51]:
tf.cast([True, False, 1==1, 0==1], tf.int32).numpy()

array([1, 0, 1, 0])

### 8. stack

In [52]:
x = [1,4]
y = [2,5]
z = [3,6]
tf.stack([x,y,z]).numpy()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
tf.stack([x,y,z], axis=1).numpy()

array([[1, 2, 3],
       [4, 5, 6]])

### 9. Ones and Zeros like

In [54]:
x = [[0,1,2],
     [2,1,0]]
tf.ones_like(x).numpy()

array([[1, 1, 1],
       [1, 1, 1]])

In [55]:
tf.zeros_like(x).numpy()

array([[0, 0, 0],
       [0, 0, 0]])

### 10. zip

In [56]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [58]:
for x,y,z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
